
### 비밀번호 변경 요청
PATCH http://localhost:8080/v1/member/change-password
Content-Type: application/json
Authorization: eyJraWQiOiJrZXkxIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0MTIzQG5hdmVyLmNvbSIsImlhdCI6MTcwNTE2MTY4MSwiZXhwIjoxNzA1MzA1NjgxfQ.svYQoryom9WaYr3KA_2TYOMzZW0uXgK00pAYOp-KiBU

{
  "newPassword": "123456789"
}


### 비밀번호 체크 요청
POST http://localhost:8080/v1/member/check-password
Content-Type: application/json
Authorization: eyJraWQiOiJrZXkxIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0MTIzQG5hdmVyLmNvbSIsImlhdCI6MTcwNTE2MTY4MSwiZXhwIjoxNzA1MzA1NjgxfQ.svYQoryom9WaYr3KA_2TYOMzZW0uXgK00pAYOp-KiBU

{
  "currentPassword": "123456"
}


### 이메일 체크 요청
POST http://localhost:8080/v1/member/check-email
Content-Type: application/json
Authorization: eyJraWQiOiJrZXkxIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0MTIzQG5hdmVyLmNvbSIsImlhdCI6MTcwNTE2MTY4MSwiZXhwIjoxNzA1MzA1NjgxfQ.svYQoryom9WaYr3KA_2TYOMzZW0uXgK00pAYOp-KiBU

{
  "email": "test123@naver.com"
}